# Generated by Django 5.1.6 on 2025-09-24 12:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheObservation',
            fields=[
                ('num_fiche', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee', models.IntegerField()),
                ('chemin_image', models.CharField(blank=True, max_length=255)),
                ('chemin_json', models.CharField(blank=True, max_length=255)),
                ('transcription', models.BooleanField(default=False)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='taxonomy.espece')),
                ('observateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CausesEchec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Aucune cause identifiée')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='causes_echec', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='Nid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_prec_t_meme_couple', models.BooleanField(default=False)),
                ('hauteur_nid', models.IntegerField(blank=True, default=0, null=True)),
                ('hauteur_couvert', models.IntegerField(blank=True, default=0, null=True)),
                ('details_nid', models.TextField(blank=True, default='Aucun détail')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nid', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateTimeField(db_index=True)),
                ('nombre_oeufs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_poussins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('observations', models.TextField(blank=True, default='Aucune observation')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='Remarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarque', models.CharField(default='RAS', max_length=200)),
                ('date_remarque', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarques', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_oeuf_pondu_jour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('premier_oeuf_pondu_mois', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('premier_poussin_eclos_jour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('premier_poussin_eclos_mois', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('premier_poussin_volant_jour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('premier_poussin_volant_mois', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('nombre_oeufs_pondus', models.PositiveSmallIntegerField(default=0)),
                ('nombre_oeufs_eclos', models.PositiveSmallIntegerField(default=0)),
                ('nombre_oeufs_non_eclos', models.PositiveSmallIntegerField(default=0)),
                ('nombre_poussins', models.PositiveSmallIntegerField(default=0)),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='observations.ficheobservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='ficheobservation',
            index=models.Index(fields=['observateur', 'date_creation'], name='observation_observa_4502fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('premier_oeuf_pondu_jour__isnull', True), ('premier_oeuf_pondu_mois__isnull', True)), models.Q(('premier_oeuf_pondu_jour__isnull', False), ('premier_oeuf_pondu_mois__isnull', False)), _connector='OR'), name='resume_premier_oeuf_pondu_jour_mois_both_or_none'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('premier_poussin_eclos_jour__isnull', True), ('premier_poussin_eclos_mois__isnull', True)), models.Q(('premier_poussin_eclos_jour__isnull', False), ('premier_poussin_eclos_mois__isnull', False)), _connector='OR'), name='resume_premier_poussin_eclos_jour_mois_both_or_none'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('premier_poussin_volant_jour__isnull', True), ('premier_poussin_volant_mois__isnull', True)), models.Q(('premier_poussin_volant_jour__isnull', False), ('premier_poussin_volant_mois__isnull', False)), _connector='OR'), name='resume_premier_poussin_volant_jour_mois_both_or_none'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_oeufs_pondus__gte', 0), ('nombre_oeufs_eclos__gte', 0), ('nombre_oeufs_non_eclos__gte', 0), ('nombre_poussins__gte', 0)), name='resume_counts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_oeufs_eclos__lte', models.F('nombre_oeufs_pondus'))), name='resume_eclos_le_pondus'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_oeufs_non_eclos__lte', models.F('nombre_oeufs_pondus'))), name='resume_non_eclos_le_pondus'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_poussins__lte', models.F('nombre_oeufs_eclos'))), name='resume_poussins_le_eclos'),
        ),
    ]
