# Generated by Django 5.1.6 on 2025-09-12 20:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_anglais', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_scientifique', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('lien_oiseau_net', models.URLField(blank=True, null=True)),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('famille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especes', to='observations.famille')),
            ],
        ),
        migrations.CreateModel(
            name='FicheObservation',
            fields=[
                ('num_fiche', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee', models.IntegerField()),
                ('chemin_image', models.CharField(blank=True, max_length=255, null=True)),
                ('chemin_json', models.CharField(blank=True, max_length=255, null=True)),
                ('transcription', models.BooleanField(default=False)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observations.espece')),
                ('observateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CausesEchec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Aucune cause identifiée', null=True)),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='causes_echec', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField()),
                ('nouvelle_valeur', models.TextField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(choices=[('fiche', 'Fiche Observation'), ('observation', 'Observation'), ('validation', 'Validation'), ('localisation', 'Localisation'), ('nid', 'Nid'), ('resume_observation', 'Résumé Observation'), ('causes_echec', 'Causes d’échec')], db_index=True, default='fiche', max_length=20)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='observations.ficheobservation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques des modifications',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(default='Non spécifiée', max_length=30)),
                ('lieu_dit', models.CharField(default='Non spécifiée', max_length=30)),
                ('departement', models.CharField(default='00', max_length=5)),
                ('coordonnees', models.CharField(default='0,0', max_length=30)),
                ('latitude', models.CharField(default='0.0', max_length=15)),
                ('longitude', models.CharField(default='0.0', max_length=15)),
                ('altitude', models.CharField(default='0', max_length=10)),
                ('paysage', models.TextField(default='Non spécifié')),
                ('alentours', models.TextField(default='Non spécifié')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='Nid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_prec_t_meme_couple', models.BooleanField(default=False)),
                ('hauteur_nid', models.IntegerField(blank=True, default=0, null=True)),
                ('hauteur_couvert', models.IntegerField(blank=True, default=0, null=True)),
                ('details_nid', models.TextField(blank=True, default='Aucun détail', null=True)),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nid', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateTimeField(db_index=True)),
                ('nombre_oeufs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_poussins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('observations', models.TextField(blank=True, default='Aucune observation', null=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='observations.ficheobservation')),
            ],
        ),
        migrations.AddField(
            model_name='famille',
            name='ordre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='observations.ordre'),
        ),
        migrations.CreateModel(
            name='Remarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarque', models.CharField(default='RAS', max_length=200)),
                ('date_remarque', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarques', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_oeuf_pondu_jour', models.IntegerField(blank=True, null=True)),
                ('premier_oeuf_pondu_mois', models.IntegerField(blank=True, null=True)),
                ('premier_poussin_eclos_jour', models.IntegerField(blank=True, null=True)),
                ('premier_poussin_eclos_mois', models.IntegerField(blank=True, null=True)),
                ('premier_poussin_volant_jour', models.IntegerField(blank=True, null=True)),
                ('premier_poussin_volant_mois', models.IntegerField(blank=True, null=True)),
                ('nombre_oeufs_pondus', models.IntegerField(default=0)),
                ('nombre_oeufs_eclos', models.IntegerField(default=0)),
                ('nombre_oeufs_non_eclos', models.IntegerField(default=0)),
                ('nombre_poussins', models.IntegerField(default=0)),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='observations.ficheobservation')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejete', 'Rejetée')], default='en_cours', max_length=10)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='observations.ficheobservation')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejete', 'Rejetée')], max_length=10)),
                ('nouveau_statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejete', 'Rejetée')], max_length=10)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='observations.validation')),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddIndex(
            model_name='ficheobservation',
            index=models.Index(fields=['observateur', 'date_creation'], name='observation_observa_4502fa_idx'),
        ),
    ]
