# Generated by Django 5.1.6 on 2025-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causesechec',
            name='description',
            field=models.TextField(blank=True, default='Aucune cause identifiée', null=True),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='alentours',
            field=models.TextField(default='Non spécifié'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='altitude',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='commune',
            field=models.CharField(default='Non spécifiée', max_length=30),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='coordonnees',
            field=models.CharField(default='0,0', max_length=30),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='departement',
            field=models.CharField(default='00', max_length=5),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='latitude',
            field=models.CharField(default='0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='longitude',
            field=models.CharField(default='0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='paysage',
            field=models.TextField(default='Non spécifié'),
        ),
        migrations.AlterField(
            model_name='nid',
            name='details_nid',
            field=models.TextField(blank=True, default='Aucun détail', null=True),
        ),
        migrations.AlterField(
            model_name='nid',
            name='hauteur_couvert',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nid',
            name='hauteur_nid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date_observation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nom',
            field=models.CharField(default='Observation sans nom', max_length=100),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observations',
            field=models.TextField(blank=True, default='Aucune observation', null=True),
        ),
    ]
