# Generated by Django 5.1.6 on 2025-09-25 10:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouvelle fiche'), ('en_cours', 'En cours de correction'), ('valide', 'Validée')], default='nouveau', max_length=20)),
                ('pourcentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_correction', to='observations.ficheobservation')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pourcentage_completion__gte', 0), ('pourcentage_completion__lte', 100)), name='etat_correction_pourcentage_valide')],
            },
        ),
    ]
