# Generated by Django 5.1.6 on 2025-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_add_etat_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatcorrection',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouvelle fiche'), ('en_edition', "En cours d'édition"), ('en_cours', 'En cours de correction'), ('valide', 'Validée')], default='nouveau', max_length=20),
        ),
    ]
