# Generated by Django 5.1.6 on 2025-03-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0002_alter_causesechec_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarque', models.CharField(default='RAS', max_length=200)),
                ('date_remarque', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarques', to='Observations.ficheobservation')),
            ],
        ),
    ]
