# Generated by Django 5.1.6 on 2025-03-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0003_remarque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='nom',
        ),
    ]
