# Generated by Django 5.1.6 on 2025-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_add_en_edition_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resumeobservation',
            name='resume_counts_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='resumeobservation',
            name='resume_eclos_le_pondus',
        ),
        migrations.RemoveConstraint(
            model_name='resumeobservation',
            name='resume_non_eclos_le_pondus',
        ),
        migrations.RemoveConstraint(
            model_name='resumeobservation',
            name='resume_poussins_le_eclos',
        ),
        migrations.AlterField(
            model_name='resumeobservation',
            name='nombre_oeufs_eclos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeobservation',
            name='nombre_oeufs_non_eclos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeobservation',
            name='nombre_oeufs_pondus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeobservation',
            name='nombre_poussins',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_oeufs_eclos__isnull', True), ('nombre_oeufs_pondus__isnull', True), ('nombre_oeufs_eclos__lte', models.F('nombre_oeufs_pondus')), _connector='OR'), name='resume_eclos_le_pondus'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_oeufs_non_eclos__isnull', True), ('nombre_oeufs_pondus__isnull', True), ('nombre_oeufs_non_eclos__lte', models.F('nombre_oeufs_pondus')), _connector='OR'), name='resume_non_eclos_le_pondus'),
        ),
        migrations.AddConstraint(
            model_name='resumeobservation',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_poussins__isnull', True), ('nombre_oeufs_eclos__isnull', True), ('nombre_poussins__lte', models.F('nombre_oeufs_eclos')), _connector='OR'), name='resume_poussins_le_eclos'),
        ),
    ]
