# Generated by Django 5.2.7 on 2025-11-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_allow_null_resume_counts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['date_observation']},
        ),
    ]
