# Generated by Django 5.2.7 on 2025-11-03 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_alter_observation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_sources/%Y/%m/%d/', verbose_name='Fichier image')),
                ('est_transcrite', models.BooleanField(db_index=True, default=False, help_text='Indique si une FicheObservation a été créée à partir de cette image.', verbose_name='Est transcrite')),
                ('date_televersement', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('fiche_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_source_originale', to='observations.ficheobservation', verbose_name="Fiche d'observation associée")),
                ('observateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_sources', to=settings.AUTH_USER_MODEL, verbose_name='Observateur')),
            ],
            options={
                'verbose_name': 'Image source',
                'verbose_name_plural': 'Images sources',
                'ordering': ['-date_televersement'],
            },
        ),
    ]
