# Generated by Django 5.2.7 on 2025-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_imagesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causesechec',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nid',
            name='details_nid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='remarque',
            name='remarque',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
