# Generated by Django 5.1.6 on 2025-03-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0006_remove_utilisateur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='lieu_dit',
            field=models.CharField(default='Non spécifiée', max_length=30),
        ),
    ]
