# Generated by Django 5.2.8 on 2025-11-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_alter_causesechec_description_alter_nid_details_nid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='heure_connue',
            field=models.BooleanField(default=True, help_text="Indique si l'heure d'observation est connue"),
        ),
    ]
