# Generated by Django 5.1.6 on 2025-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0007_remove_utilisateur_date_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_inscription',
        ),
        migrations.AlterField(
            model_name='observation',
            name='date_observation',
            field=models.DateTimeField(),
        ),
    ]
