# Generated by Django 5.2.8 on 2025-11-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_observation_heure_connue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nid',
            name='hauteur_couvert',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nid',
            name='hauteur_nid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
