# Generated by Django 5.1.6 on 2025-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0008_remove_utilisateur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_transcription',
            field=models.BooleanField(default=False),
        ),
    ]
