# Generated by Django 5.1.6 on 2025-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0009_utilisateur_est_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheobservation',
            name='chemin_json',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ficheobservation',
            name='transcription',
            field=models.BooleanField(default=False),
        ),
    ]
