# Generated by Django 5.2.8 on 2025-11-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_nid_hauteur_default_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheobservation',
            name='numero_personnel',
            field=models.IntegerField(blank=True, default=None, help_text="Numéro attribué par l'observateur", null=True, verbose_name='Numéro personnel'),
        ),
        migrations.AddField(
            model_name='nid',
            name='fiche_precedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nids_suivants', to='observations.ficheobservation', verbose_name='Fiche précédente'),
        ),
    ]
