# Generated by Django 5.2.8 on 2025-11-20 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_numero_personnel_et_fiche_precedente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='nombre_oeufs',
            field=models.IntegerField(blank=True, help_text='Laisser vide si non observé', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='nombre_poussins',
            field=models.IntegerField(blank=True, help_text='Laisser vide si non observé', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
