# Generated by Django 6.0 on 2025-12-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_allow_null_oeufs_poussins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationVerrouillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_verrouillage_jours', models.IntegerField(choices=[(1, '1 jour'), (2, '2 jours'), (5, '5 jours'), (10, '10 jours'), (0, 'Jamais (verrouillage permanent)')], default=5, help_text='Durée après laquelle une fiche verrouillée sera automatiquement débloquée. 0 = jamais.', verbose_name='Durée du verrouillage')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du verrouillage',
                'verbose_name_plural': 'Configuration du verrouillage',
            },
        ),
        migrations.AddField(
            model_name='etatcorrection',
            name='date_debut_correction',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le verrouillage a été activé', null=True, verbose_name='Date début correction'),
        ),
        migrations.AddField(
            model_name='etatcorrection',
            name='en_correction_par',
            field=models.ForeignKey(blank=True, help_text='Reviewer qui a verrouillé la fiche pour correction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_en_correction', to=settings.AUTH_USER_MODEL, verbose_name='En correction par'),
        ),
    ]
