# Generated by Django 5.1.6 on 2025-04-20 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0011_alter_ficheobservation_observateur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ficheobservation',
            index=models.Index(fields=['observateur', 'date_creation'], name='Observation_observa_6451d8_idx'),
        ),
    ]
