# Generated by Django 6.0.1 on 2026-01-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_configurationverrouillage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarque',
            name='remarque',
            field=models.TextField(blank=True, default=''),
        ),
    ]
