# Generated by Django 5.1.6 on 2025-04-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observations', '0012_ficheobservation_observation_observa_6451d8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date_observation',
            field=models.DateTimeField(db_index=True),
        ),
    ]
