# Generated by Django 6.0.1 on 2026-01-23 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_alter_remarque_remarque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueVerrouillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(help_text='Date à laquelle le correcteur a verrouillé la fiche', verbose_name='Date début correction')),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date de libération du verrou (null = encore verrouillé)', null=True, verbose_name='Date fin correction')),
                ('motif_liberation', models.CharField(blank=True, choices=[('timeout', 'Timeout expiré'), ('validation', 'Fiche validée'), ('manuel', 'Déverrouillage manuel'), ('changement_correcteur', 'Changement de correcteur')], max_length=30, null=True, verbose_name='Motif de libération')),
                ('correcteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Correcteur')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_verrouillages', to='observations.ficheobservation', verbose_name='Fiche')),
            ],
            options={
                'verbose_name': 'Historique de verrouillage',
                'verbose_name_plural': 'Historiques de verrouillage',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['fiche', '-date_debut'], name='observation_fiche_i_6ec617_idx')],
            },
        ),
    ]
