# Generated by Django 6.0.1 on 2026-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_historiqueverrouillage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueverrouillage',
            name='motif_liberation',
            field=models.CharField(blank=True, choices=[('timeout', 'Timeout expiré'), ('validation', 'Fiche validée'), ('manuel', 'Déverrouillage manuel'), ('changement_correcteur', 'Changement de correcteur')], default='', max_length=30, verbose_name='Motif de libération'),
        ),
    ]
