# Generated by Django 6.0.2 on 2026-03-22 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_add_incertitude_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date_note', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_correction', to=settings.AUTH_USER_MODEL)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_correction', to='observations.ficheobservation')),
            ],
        ),
    ]
