# Generated by Django 5.2.8 on 2025-11-23 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_brut_recto', models.CharField(help_text='Chemin du scan brut recto', max_length=255)),
                ('fichier_brut_verso', models.CharField(blank=True, help_text='Chemin du scan brut verso (optionnel si fiche recto seulement)', max_length=255)),
                ('fichier_fusionne', models.ImageField(help_text='Image fusionnée recto+verso optimisée pour OCR', unique=True, upload_to='prepared_images/%Y/')),
                ('operations_effectuees', models.JSONField(default=dict, help_text='Liste des opérations de traitement (rotation, crop, contraste, etc.)')),
                ('date_preparation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la préparation')),
                ('notes', models.TextField(blank=True, help_text='Notes ou remarques sur cette préparation')),
                ('operateur', models.ForeignKey(help_text='Utilisateur ayant effectué la préparation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparations_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Préparation d'image",
                'verbose_name_plural': "Préparations d'images",
                'ordering': ['-date_preparation'],
                'indexes': [models.Index(fields=['date_preparation'], name='ingest_prep_date_pr_ac65bb_idx'), models.Index(fields=['operateur'], name='ingest_prep_operate_332676_idx')],
            },
        ),
    ]
