# Generated by Django 6.0 on 2026-01-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_preparationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='espececandidate',
            name='code_gonm_transcrit',
            field=models.CharField(blank=True, default='', help_text='Code GONM extrait du JSON (champ n_espece)', max_length=10),
        ),
    ]
