# Generated by Django 5.1.6 on 2025-09-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_anglais', models.CharField(blank=True, max_length=100)),
                ('nom_scientifique', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(blank=True, max_length=50)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('lien_oiseau_net', models.URLField(blank=True)),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especes', to='taxonomy.famille')),
            ],
        ),
        migrations.AddField(
            model_name='famille',
            name='ordre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='taxonomy.ordre'),
        ),
    ]
