# Generated by Django 6.0 on 2025-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espece',
            name='code_GONM',
            field=models.CharField(blank=True, help_text="Code GONM de l'espèce", max_length=10),
        ),
    ]
