# Generated by Django 6.0 on 2026-01-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_espece_code_gonm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espece',
            old_name='code_GONM',
            new_name='code_gonm',
        ),
    ]
