# Generated by Django 6.0.1 on 2026-01-26 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message')),
                ('url_source', models.CharField(blank=True, max_length=500, verbose_name="URL d'origine")),
                ('category', models.CharField(choices=[('BUG', 'Bug / Problème technique'), ('IDEA', 'Suggestion / Idée'), ('DATA', 'Donnée erronée'), ('QUESTION', 'Question'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie (IA)')),
                ('urgency', models.IntegerField(default=1, verbose_name='Urgence (1-5)')),
                ('sentiment', models.CharField(blank=True, max_length=50, verbose_name='Sentiment')),
                ('ai_summary', models.CharField(blank=True, max_length=200, verbose_name='Résumé IA')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('READ', 'Lu'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('ARCHIVED', 'Archivé')], default='NEW', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
