# Generated by Django 6.0.1 on 2026-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Note / Décision Administrateur'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_public_response',
            field=models.BooleanField(default=False, verbose_name='Rendre la note publique'),
        ),
    ]
