# Generated by Django 6.0.1 on 2026-01-29 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_admin_note_feedback_is_public_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-last_activity'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dernière activité'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Note / Décision Administrateur (Legacy)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('READ', 'Lu'), ('IN_PROGRESS', 'En cours'), ('WAITING_USER', "En attente d'infos"), ('RESOLVED', 'Résolu'), ('ARCHIVED', 'Archivé')], default='NEW', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='feedback.feedback', verbose_name='Feedback')),
            ],
            options={
                'verbose_name': 'Message de feedback',
                'verbose_name_plural': 'Messages de feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
