# Generated by Django 6.0.2 on 2026-03-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_options_feedback_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug / Problème technique'), ('IDEA', 'Suggestion / Idée'), ('DATA', 'Donnée erronée'), ('QUESTION', 'Question'), ('OCR', 'Problème OCR / Prompt Gemini'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie (IA)'),
        ),
    ]
