# Generated by Django 6.0.2 on 2026-03-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_add_ocr_category_and_title'),
        ('observations', '0016_add_incertitude_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fiche_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='observations.ficheobservation', verbose_name='Fiche concernée'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug / Problème technique'), ('IDEA', 'Suggestion / Idée'), ('DATA', 'Donnée erronée'), ('QUESTION', 'Question'), ('OCR', 'Problème OCR / Prompt Gemini'), ('INGEST', "Problème d'import / Algorithme"), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie (IA)'),
        ),
    ]
