# Generated by Django 5.2.7 on 2025-10-13 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('demande_compte', 'Demande de compte'), ('compte_valide', 'Compte validé'), ('compte_refuse', 'Compte refusé'), ('info', 'Information'), ('warning', 'Avertissement')], default='info', max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, help_text='URL relative vers la ressource concernée', max_length=255, null=True, verbose_name='Lien')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('utilisateur_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_le_concernant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'est_lue'], name='accounts_no_destina_5212ff_idx'), models.Index(fields=['type_notification'], name='accounts_no_type_no_359413_idx')],
            },
        ),
    ]
