# Generated by Django 5.2.7 on 2025-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, default='', help_text='URL relative vers la ressource concernée', max_length=255, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur avec cette adresse email existe déjà.'}, max_length=254, unique=True, verbose_name='adresse email'),
        ),
    ]
