# Generated by Django 5.2.8 on 2025-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email_unique_et_lien_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_refuse',
            field=models.BooleanField(default=False),
        ),
    ]
