# Generated by Django 6.0.2 on 2026-03-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_utilisateur_est_refuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('observateur', 'Observateur'), ('reviewer', 'Reviewer'), ('super_utilisateur', 'Super Utilisateur'), ('administrateur', 'Administrateur')], default='observateur', max_length=20),
        ),
    ]
