# Generated by Django 5.2.8 on 2025-12-17 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0011_allow_null_oeufs_poussins'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_json', models.CharField(help_text='Chemin vers le fichier JSON brut de la transcription OCR', max_length=255, verbose_name='Chemin du fichier JSON')),
                ('chemin_image', models.CharField(blank=True, help_text="Chemin de l'image utilisée pour cette transcription", max_length=255, verbose_name="Chemin de l'image source")),
                ('type_image', models.CharField(choices=[('brute', 'Image brute'), ('optimisee', 'Image optimisée pour OCR')], help_text="Type de traitement appliqué à l'image", max_length=20, verbose_name="Type d'image")),
                ('modele_ocr', models.CharField(choices=[('gemini_flash', 'Gemini Flash'), ('gemini_1.5_pro', 'Gemini 1.5 Pro'), ('gemini_2_pro', 'Gemini 2.0 Pro'), ('gemini_2_flash', 'Gemini 2.0 Flash')], help_text="Modèle d'IA utilisé pour la transcription", max_length=50, verbose_name='Modèle OCR')),
                ('date_transcription', models.DateTimeField(auto_now_add=True, verbose_name='Date de transcription')),
                ('statut_evaluation', models.CharField(choices=[('non_evaluee', 'Non évaluée'), ('en_cours', 'Évaluation en cours'), ('evaluee', 'Évaluée'), ('erreur', "Erreur lors de l'évaluation")], default='non_evaluee', max_length=20, verbose_name="Statut de l'évaluation")),
                ('date_evaluation', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'évaluation")),
                ('score_global', models.FloatField(blank=True, help_text='Score de similarité global entre OCR et vérité terrain (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score global (%)')),
                ('nombre_champs_corrects', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de champs corrects')),
                ('nombre_champs_total', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de champs total')),
                ('nombre_erreurs_dates', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erreurs sur les dates')),
                ('nombre_erreurs_nombres', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erreurs sur les nombres')),
                ('nombre_erreurs_texte', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erreurs sur le texte')),
                ('nombre_erreurs_especes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erreurs sur les espèces')),
                ('nombre_erreurs_lieux', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erreurs sur les lieux')),
                ('details_comparaison', models.JSONField(blank=True, help_text='Détails des différences champ par champ au format JSON', null=True, verbose_name='Détails de comparaison')),
                ('temps_traitement_secondes', models.FloatField(blank=True, help_text='Durée du traitement OCR en secondes', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Temps de traitement (s)')),
                ('notes_evaluation', models.TextField(blank=True, help_text='Notes et observations manuelles', verbose_name="Notes d'évaluation")),
                ('fiche', models.ForeignKey(help_text="Fiche d'observation corrigée manuellement (vérité terrain)", on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions_ocr_pilot', to='observations.ficheobservation', verbose_name='Fiche de référence')),
            ],
            options={
                'verbose_name': '[PILOTE] Transcription OCR',
                'verbose_name_plural': '[PILOTE] Transcriptions OCR',
                'db_table': 'pilot_transcription_ocr',
                'ordering': ['-date_transcription'],
                'indexes': [models.Index(fields=['fiche', 'modele_ocr'], name='pilot_trans_fiche_i_0e707c_idx'), models.Index(fields=['statut_evaluation'], name='pilot_trans_statut__7be669_idx'), models.Index(fields=['score_global'], name='pilot_trans_score_g_a3a215_idx')],
            },
        ),
    ]
