# Generated by Django 5.2.8 on 2025-12-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_allow_null_oeufs_poussins'),
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionocr',
            name='fiche',
            field=models.ForeignKey(blank=True, help_text="Fiche d'observation corrigée manuellement (vérité terrain)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions_ocr_pilot', to='observations.ficheobservation', verbose_name='Fiche de référence'),
        ),
    ]
