# Generated by Django 5.2.8 on 2025-12-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_alter_transcriptionocr_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionocr',
            name='modele_ocr',
            field=models.CharField(choices=[('gemini_3_flash', 'Gemini 3 Flash'), ('gemini_3_pro', 'Gemini 3 Pro'), ('gemini_2.5_pro', 'Gemini 2.5 Pro'), ('gemini_2.5_flash_lite', 'Gemini 2.5 Flash-Lite')], help_text="Modèle d'IA utilisé pour la transcription", max_length=50, verbose_name='Modèle OCR'),
        ),
    ]
