# Generated by Django 5.1.6 on 2025-09-24 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejete', 'Rejetée')], default='en_cours', max_length=10)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='observations.ficheobservation')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejete', 'Rejetée')], max_length=10)),
                ('nouveau_statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejete', 'Rejetée')], max_length=10)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='review.validation')),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
    ]
