# Generated by Django 5.1.6 on 2025-09-24 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField()),
                ('nouvelle_valeur', models.TextField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(choices=[('fiche', 'Fiche Observation'), ('observation', 'Observation'), ('validation', 'Validation'), ('localisation', 'Localisation'), ('nid', 'Nid'), ('resume_observation', 'Résumé Observation'), ('causes_echec', "Causes d'échec")], db_index=True, default='fiche', max_length=20)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='observations.ficheobservation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques des modifications',
                'ordering': ['-date_modification'],
            },
        ),
    ]
