# Generated by Django 5.2.7 on 2025-10-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquemodification',
            name='categorie',
            field=models.CharField(choices=[('fiche', 'Fiche Observation'), ('observation', 'Observation'), ('validation', 'Validation'), ('localisation', 'Localisation'), ('nid', 'Nid'), ('resume_observation', 'Résumé Observation'), ('causes_echec', "Causes d'échec"), ('remarque', 'Remarque')], db_index=True, default='fiche', max_length=20),
        ),
    ]
