# Generated by Django 5.1.6 on 2025-09-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(default='Non spécifiée', max_length=30)),
                ('lieu_dit', models.CharField(default='Non spécifiée', max_length=30)),
                ('departement', models.CharField(default='00', max_length=5)),
                ('coordonnees', models.CharField(default='0,0', max_length=30)),
                ('latitude', models.CharField(default='0.0', max_length=15)),
                ('longitude', models.CharField(default='0.0', max_length=15)),
                ('altitude', models.CharField(default='0', max_length=10)),
                ('paysage', models.TextField(default='Non spécifié')),
                ('alentours', models.TextField(default='Non spécifié')),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='observations.ficheobservation')),
            ],
        ),
    ]
