# Generated by Django 5.1.6 on 2025-10-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='code_insee',
            field=models.CharField(blank=True, help_text='Code INSEE de la commune', max_length=5),
        ),
        migrations.AddField(
            model_name='localisation',
            name='precision_gps',
            field=models.IntegerField(default=5000, help_text='Précision estimée en mètres (ex: 10m pour GPS terrain, 5000m pour commune)'),
        ),
        migrations.AddField(
            model_name='localisation',
            name='source_coordonnees',
            field=models.CharField(choices=[('gps_terrain', 'GPS de terrain'), ('geocodage_auto', 'Géocodage automatique'), ('geocodage_manuel', 'Géocodage manuel'), ('carte', 'Pointé sur carte'), ('base_locale', 'Base locale des communes'), ('nominatim', 'Nominatim (OSM)')], default='geocodage_auto', max_length=50),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='commune',
            field=models.CharField(default='Non spécifiée', max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='departement',
            field=models.CharField(default='00', max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='lieu_dit',
            field=models.CharField(blank=True, default='Non spécifiée', max_length=100),
        ),
        migrations.CreateModel(
            name='CommuneFrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('code_insee', models.CharField(help_text='Code INSEE de la commune', max_length=5, unique=True)),
                ('code_postal', models.CharField(db_index=True, max_length=5)),
                ('departement', models.CharField(max_length=100)),
                ('code_departement', models.CharField(db_index=True, max_length=3)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie en km²', max_digits=10, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commune française',
                'verbose_name_plural': 'Communes françaises',
                'db_table': 'geo_commune_france',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom', 'code_departement'], name='geo_commune_nom_811dd7_idx'), models.Index(fields=['code_postal'], name='geo_commune_code_po_e99b3e_idx')],
            },
        ),
    ]
