# Generated by Django 5.1.6 on 2025-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_localisation_code_insee_localisation_precision_gps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communefrance',
            name='altitude',
            field=models.IntegerField(blank=True, help_text='Altitude en mètres (centre de la commune)', null=True),
        ),
    ]
