# Generated by Django 5.1.6 on 2025-10-05 19:03

from django.db import migrations, models
import re


def nettoyer_altitudes(apps, schema_editor):
    """Nettoie les valeurs d'altitude avant conversion en IntegerField"""
    Localisation = apps.get_model('geo', 'Localisation')

    for loc in Localisation.objects.all():
        # Extraire les chiffres de la valeur actuelle
        if loc.altitude:
            # Supprimer 'm', espaces, et autres caractères non numériques
            valeur_nettoyee = re.sub(r'[^\d.-]', '', str(loc.altitude))
            try:
                # Convertir en entier
                loc.altitude = str(int(float(valeur_nettoyee))) if valeur_nettoyee else '0'
            except (ValueError, TypeError):
                loc.altitude = '0'
        else:
            loc.altitude = '0'
        loc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_communefrance_altitude'),
    ]

    operations = [
        # Étape 1 : Nettoyer les données existantes
        migrations.RunPython(nettoyer_altitudes, reverse_code=migrations.RunPython.noop),

        # Étape 2 : Changer le type de champ
        migrations.AlterField(
            model_name='localisation',
            name='altitude',
            field=models.IntegerField(default=0, help_text='Altitude en mètres'),
        ),
    ]
