# Generated by Django 5.2.7 on 2025-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_localisation_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='alentours',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='lieu_dit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='paysage',
            field=models.TextField(blank=True, default=''),
        ),
    ]
