# Generated by Django 5.2.8 on 2025-11-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_localisation_alentours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communefrance',
            name='ajoutee_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant ajouté cette commune manuellement', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communefrance',
            name='autres_noms',
            field=models.TextField(blank=True, help_text="Autres appellations ou anciens noms (séparés par des virgules). Ex: 'Les Praz, Les Praz-de-Chamonix' pour une commune fusionnée"),
        ),
        migrations.AddField(
            model_name='communefrance',
            name='commentaire',
            field=models.TextField(blank=True, help_text="Notes sur l'origine (fusion, ancienne commune, erreur OCR récurrente, etc.)"),
        ),
        migrations.AddField(
            model_name='communefrance',
            name='commune_actuelle',
            field=models.ForeignKey(blank=True, help_text='Si cette commune a fusionné, référence vers la commune actuelle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_communes', to='geo.communefrance'),
        ),
        migrations.AddField(
            model_name='communefrance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'ajout dans la base de données", null=True),
        ),
        migrations.AddField(
            model_name='communefrance',
            name='source_ajout',
            field=models.CharField(choices=[('api_geo', 'API Découpage administratif'), ('nominatim', 'Nominatim (OpenStreetMap)'), ('manuel', 'Ajout manuel par administrateur')], default='api_geo', help_text="Source d'origine des données", max_length=50),
        ),
    ]
