# Generated by Django 5.2.8 on 2025-11-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_communefrance_ajoutee_par_communefrance_autres_noms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communefrance',
            name='commune_actuelle',
        ),
        migrations.CreateModel(
            name='AncienneCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, help_text="Nom de l'ancienne commune", max_length=200)),
                ('code_insee', models.CharField(help_text="Code INSEE (désormais inactif) de l'ancienne commune", max_length=5, unique=True)),
                ('code_postal', models.CharField(blank=True, help_text='Ancien code postal', max_length=5)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('code_departement', models.CharField(db_index=True, max_length=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Latitude du centre de l'ancienne commune", max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text="Longitude du centre de l'ancienne commune", max_digits=9, null=True)),
                ('altitude', models.IntegerField(blank=True, help_text='Altitude en mètres', null=True)),
                ('date_fusion', models.DateField(blank=True, help_text='Date de la fusion (arrêté préfectoral)', null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Notes sur la fusion ou particularités historiques')),
                ('date_import', models.DateTimeField(auto_now_add=True, help_text="Date d'import dans la base", null=True)),
                ('commune_actuelle', models.ForeignKey(help_text='Commune actuelle résultant de la fusion', on_delete=django.db.models.deletion.CASCADE, related_name='anciennes_communes', to='geo.communefrance')),
            ],
            options={
                'verbose_name': 'Ancienne commune (fusionnée)',
                'verbose_name_plural': 'Anciennes communes (fusionnées)',
                'db_table': 'geo_ancienne_commune',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='geo_ancienn_nom_dfad02_idx'), models.Index(fields=['code_insee'], name='geo_ancienn_code_in_c9a42f_idx'), models.Index(fields=['code_departement'], name='geo_ancienn_code_de_2af2a5_idx')],
            },
        ),
    ]
