# Generated by Django 5.2.8 on 2025-11-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_remove_communefrance_commune_actuelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='commune_saisie',
            field=models.CharField(blank=True, default='', help_text="Nom exact de la commune saisi par l'observateur (peut être une ancienne commune)", max_length=100),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='commune',
            field=models.CharField(blank=True, default='', help_text='Nom de la commune actuelle (normalisé)', max_length=100),
        ),
    ]
