# Generated by Django 6.0.2 on 2026-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_localisation_commune_saisie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='commune_non_resolue',
            field=models.BooleanField(default=False, help_text="True si la commune OCR n'a pas été trouvée dans la base locale lors de l'import"),
        ),
        migrations.AddField(
            model_name='localisation',
            name='commune_ocr_brute',
            field=models.CharField(blank=True, default='', help_text="Valeur brute de la commune telle que transcrite par l'OCR", max_length=200),
        ),
    ]
