# Generated by Django 5.1.6 on 2025-09-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionBrute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_source', models.CharField(max_length=255, unique=True)),
                ('json_brut', models.JSONField()),
                ('date_importation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EspeceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_transcrit', models.CharField(max_length=100, unique=True)),
                ('validation_manuelle', models.BooleanField(default=False)),
                ('score_similarite', models.FloatField(default=0.0, help_text='Score de similarité en pourcentage (0-100%)')),
                ('espece_validee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.espece')),
            ],
        ),
        migrations.CreateModel(
            name='ImportationEnCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('erreur', 'Erreur détectée'), ('complete', 'importation complétée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('espece_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importation.espececandidate')),
                ('fiche_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.ficheobservation')),
                ('observateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transcription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importation.transcriptionbrute')),
            ],
        ),
    ]
