"""
Django settings for observations_nids project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from types import ModuleType
from typing import Any

from dotenv import load_dotenv

# ✅ Import Pydantic settings
from .config import get_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ Load environment variables from .env file
load_dotenv(dotenv_path=os.path.join(BASE_DIR, ".env"))


# ✅ Get settings from environment variables
settings = get_settings()

# ALLOWED_HOSTS
# Use ALLOWED_HOSTS from settings object which is loaded from config.py
ALLOWED_HOSTS = settings.ALLOWED_HOSTS

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG

# Environment identifier (production, pilote, development)
ENVIRONMENT = settings.ENVIRONMENT

_local: ModuleType | None  # <- type déclaré une fois

# Surcharge via settings_local.py (facultatif)
try:
    from . import settings_local as _local  # type: ignore
except ImportError:
    _local = None

if _local is not None:
    DEBUG = getattr(_local, "DEBUG", DEBUG)
    SECRET_KEY = getattr(_local, "SECRET_KEY", SECRET_KEY)
    ALLOWED_HOSTS = getattr(_local, "ALLOWED_HOSTS", ALLOWED_HOSTS)


AUTH_USER_MODEL = 'accounts.Utilisateur'
LOGIN_REDIRECT_URL = '/'

# Durée de session : 3600 secondes (1 heure)
SESSION_COOKIE_AGE = settings.SESSION_COOKIE_AGE
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Déconnexion si l'utilisateur ferme son navigateur

# Celery Configuration - utilise les paramètres de pydantic
# Celery Configuration - utilise les paramètres de pydantic
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # settings.celery.broker_url
# CELERY_RESULT_BACKEND = settings.celery.result_backend
# CELERY_ACCEPT_CONTENT = settings.celery.accept_content
# CELERY_TASK_SERIALIZER = settings.celery.task_serializer
# CELERY_RESULT_SERIALIZER = settings.celery.result_serializer
# CELERY_TIMEZONE = settings.celery.timezone
# CELERY_TASK_TRACK_STARTED = settings.celery.task_track_started
# CELERY_TASK_TIME_LIMIT = settings.celery.task_time_limit
# CELERY_WORKER_HIJACK_ROOT_LOGGER = settings.celery.worker_hijack_root_logger

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requis pour django-helpdesk
    'django.contrib.humanize',
    # 'django_extensions' déplacé dans settings_local.py (dev uniquement)
    'accounts.apps.AccountsConfig',
    'core.apps.CoreConfig',
    'taxonomy.apps.TaxonomyConfig',
    'geo.apps.GeoConfig',
    'observations.apps.ObservationsConfig',
    'review.apps.ReviewConfig',
    'ingest.apps.IngestConfig',
    'audit.apps.AuditConfig',
    'bootstrap4form',  # Required for nicer formatting of forms with the default templates
    'crispy_forms',  # Add crispy_forms
    'crispy_bootstrap5',  # Add crispy_bootstrap5 for Bootstrap 5 integration
    'rest_framework',  # required for the API
    'helpdesk',
    'helpdesk_custom.apps.HelpdeskCustomConfig',  # Personnalisation de Helpdesk
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'observations.middleware.SessionExpiryMiddleware',
]

ROOT_URLCONF = 'observations_nids.urls'


# Configurez les adresses IP autorisées à voir la toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

# Configuration optionnelle
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # Affiche toujours la toolbar en développement
    'RENDER_PANELS': True,  # Force le rendu synchrone des panneaux (fix pour v6.0.0)
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
                'observations_nids.context_processors.environment',
            ],
        },
    },
]

WSGI_APPLICATION = 'observations_nids.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = settings.get_database_config()

# Surcharge depuis settings_local.py si présent
if _local is not None and hasattr(_local, 'DATABASES'):
    DATABASES = _local.DATABASES


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

LOGIN_URL = 'observations:login'

# --- Static & Media configuration (managed for dev/prod) ---
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT", os.path.join(BASE_DIR, "staticfiles"))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

# Surcharge depuis settings_local.py si présent
if _local is not None:
    STATIC_ROOT = getattr(_local, "STATIC_ROOT", STATIC_ROOT)
    MEDIA_ROOT = getattr(_local, "MEDIA_ROOT", MEDIA_ROOT)
# --- End static/media ---

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Logging configuration (centralized, uses DJANGO_LOG_DIR env var in prod) ---

DEFAULT_LOG_DIR = os.path.join(BASE_DIR, 'observations', 'logs')
LOG_DIR = os.environ.get("DJANGO_LOG_DIR", DEFAULT_LOG_DIR)

# Surcharge depuis settings_local.py si présent
if _local is not None:
    LOG_DIR = getattr(_local, "LOG_DIR", LOG_DIR)

# Création du dossier logs s'il n'existe pas (seulement si dans BASE_DIR)
try:
    if str(LOG_DIR).startswith(str(BASE_DIR)):
        Path(LOG_DIR).mkdir(parents=True, exist_ok=True)
except Exception:
    pass

LOGGING: dict[str, Any] = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{module}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_debug.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'observations': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Surcharge du niveau de log depuis settings_local.py si présent
if _local is not None and hasattr(_local, 'LOG_LEVEL'):
    LOGGING['handlers']['file']['level'] = _local.LOG_LEVEL
    LOGGING['loggers']['django']['level'] = _local.LOG_LEVEL
# --- End Logging ---


# Lire la version du fichier version.txt
VERSION_FILE = os.path.join(BASE_DIR, "version.txt")
try:
    with open(VERSION_FILE) as f:
        VERSION = f.read().strip()
except FileNotFoundError:
    VERSION = "0.0.0"  # Valeur par défaut en cas d'erreur

# --- Email Configuration ---
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@observations-nids.fr')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', '')

# Surcharge depuis settings_local.py si présent
if _local is not None:
    EMAIL_BACKEND = getattr(_local, 'EMAIL_BACKEND', EMAIL_BACKEND)
    EMAIL_HOST = getattr(_local, 'EMAIL_HOST', EMAIL_HOST)
    EMAIL_PORT = getattr(_local, 'EMAIL_PORT', EMAIL_PORT)
    EMAIL_USE_TLS = getattr(_local, 'EMAIL_USE_TLS', EMAIL_USE_TLS)
    EMAIL_HOST_USER = getattr(_local, 'EMAIL_HOST_USER', EMAIL_HOST_USER)
    EMAIL_HOST_PASSWORD = getattr(_local, 'EMAIL_HOST_PASSWORD', EMAIL_HOST_PASSWORD)
    DEFAULT_FROM_EMAIL = getattr(_local, 'DEFAULT_FROM_EMAIL', DEFAULT_FROM_EMAIL)
    ADMIN_EMAIL = getattr(_local, 'ADMIN_EMAIL', ADMIN_EMAIL)
# --- End Email Configuration ---

# Active Debug Toolbar uniquement si défini dans settings_local ou .env
try:
    from .settings_local import USE_DEBUG_TOOLBAR
except (ImportError, AttributeError):
    USE_DEBUG_TOOLBAR = settings.USE_DEBUG_TOOLBAR

# settings.py (à la toute fin)
if USE_DEBUG_TOOLBAR:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1']

# django-helpdesk settings definition
HELPDESK_TEAMS_MODE_ENABLED = False
SITE_ID = 1

# 🔒 Sécurité : Désactiver l'accès public
# Seuls les utilisateurs connectés peuvent accéder à Helpdesk
HELPDESK_SUBMIT_A_TICKET_PUBLIC = False
HELPDESK_VIEW_A_TICKET_PUBLIC = False

# Utiliser nos formulaires personnalisés
HELPDESK_PUBLIC_TICKET_FORM_CLASS = 'helpdesk_custom.forms.CustomPublicTicketForm'
HELPDESK_TICKET_FORM_CLASS = 'helpdesk_custom.forms.CustomTicketForm'

# Crispy Forms Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
