"""
Django settings for Observations_Nids project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

from django.template.context_processors import media


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^tzqm_vr2-7f#2p10rehlk4pr9!z8z^!3atbbwq@2!%h_$n2f0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Surcharge via settings_local.py (facultatif)
try:
    from .settings_local import DEBUG as local_debug
    DEBUG = local_debug
except (ImportError, AttributeError):
    pass


AUTH_USER_MODEL = 'Observations.Utilisateur'
LOGIN_REDIRECT_URL = '/'

# Durée de session : 3600 secondes (1 heure)
SESSION_COOKIE_AGE = 3600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Déconnexion si l’utilisateur ferme son navigateur

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'Observations.apps.ObservationsConfig',
    'Importation.apps.ImportationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Observations.middleware.SessionExpiryMiddleware',
]

ROOT_URLCONF = 'Observations_Nids.urls'


# Configurez les adresses IP autorisées à voir la toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

# Configuration optionnelle
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # Affiche toujours la toolbar en développement
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Observations' / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Observations_Nids.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'NidsObservation',  # Nom de ta base de données
        'USER': 'jms',      # Nom d'utilisateur MariaDB
        'PASSWORD': 'pointeur', # Mot de passe MariaDB
        'HOST': '192.168.1.176',    # Adresse IP du Raspberry Pi
        'PORT': '3306',             # Port par défaut de MariaDB
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

LOGIN_URL = '/login/'

STATIC_URL = '/static/'
# Dossier où Django trouvera les fichiers statiques de l'application
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "Observations", "static"),  # Corrige ici
]

# Dossier où Django collectera tous les fichiers statiques pour la mise en production
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Dossier où seront stocké les fichiers jpg
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Chemin du dossier logs dans l'application Observations
LOG_DIR = os.path.join(BASE_DIR, 'Observations', 'logs')

# Création du dossier logs s'il n'existe pas
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{module}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'ignore_debug_toolbar_errors': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not (
                'django.template.base.VariableDoesNotExist' in record.getMessage()
                and 'toolbar' in record.getMessage()
            ),
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django_debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['ignore_debug_toolbar_errors'],
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'Observations': {  # Application principale
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.template': {
            'handlers': ['console'],
            'level': 'INFO',  # Augmenter à INFO pour réduire les messages de debug inutiles
            'propagate': False,
        },
    },
}


# Lire la version du fichier version.txt
VERSION_FILE = os.path.join(BASE_DIR, "version.txt")
try:
    with open(VERSION_FILE, "r") as f:
        VERSION = f.read().strip()
except FileNotFoundError:
    VERSION = "0.0.0"  # Valeur par défaut en cas d'erreur

# Active Debug Toolbar uniquement si défini dans settings_local
try:
    from .settings_local import USE_DEBUG_TOOLBAR
except (ImportError, AttributeError):
    USE_DEBUG_TOOLBAR = False

# settings.py (à la toute fin)
if USE_DEBUG_TOOLBAR:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1']