"""
Django settings for observations_nids project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from types import ModuleType

from dotenv import load_dotenv

# âœ… Import Pydantic settings
from .config import get_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# âœ… Load environment variables from .env file
load_dotenv(dotenv_path=os.path.join(BASE_DIR, ".env"))


# âœ… Get settings from environment variables
settings = get_settings()

# ALLOWED_HOSTS
# Use ALLOWED_HOSTS from settings object which is loaded from config.py
ALLOWED_HOSTS = settings.ALLOWED_HOSTS

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG

_local: ModuleType | None  # <- type déclaré une fois

# Surcharge via settings_local.py (facultatif)
try:
    from . import settings_local as _local  # type: ignore
except ImportError:
    _local = None

if _local is not None:
    DEBUG = getattr(_local, "DEBUG", DEBUG)
    SECRET_KEY = getattr(_local, "SECRET_KEY", SECRET_KEY)
    ALLOWED_HOSTS = getattr(_local, "ALLOWED_HOSTS", ALLOWED_HOSTS)


AUTH_USER_MODEL = 'administration.Utilisateur'
LOGIN_REDIRECT_URL = '/'

# DurÃ©e de session : 3600 secondes (1 heure)
SESSION_COOKIE_AGE = settings.SESSION_COOKIE_AGE
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # DÃ©connexion si lâ€™utilisateur ferme son navigateur

# Celery Configuration - utilise les paramÃ¨tres de pydantic
# Celery Configuration - utilise les paramÃ¨tres de pydantic
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # settings.celery.broker_url
# CELERY_RESULT_BACKEND = settings.celery.result_backend
# CELERY_ACCEPT_CONTENT = settings.celery.accept_content
# CELERY_TASK_SERIALIZER = settings.celery.task_serializer
# CELERY_RESULT_SERIALIZER = settings.celery.result_serializer
# CELERY_TIMEZONE = settings.celery.timezone
# CELERY_TASK_TRACK_STARTED = settings.celery.task_track_started
# CELERY_TASK_TIME_LIMIT = settings.celery.task_time_limit
# CELERY_WORKER_HIJACK_ROOT_LOGGER = settings.celery.worker_hijack_root_logger

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'administration.apps.AdministrationConfig',
    'observations.apps.ObservationsConfig',
    'importation.apps.ImportationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'observations.middleware.SessionExpiryMiddleware',
]

ROOT_URLCONF = 'observations_nids.urls'


# Configurez les adresses IP autorisÃ©es Ã  voir la toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

# Configuration optionnelle
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # Affiche toujours la toolbar en dÃ©veloppement
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'observations_nids.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = settings.get_database_config()


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

LOGIN_URL = 'login'

STATIC_URL = '/static/'
# Dossier oÃ¹ Django trouvera les fichiers statiques de l'application
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "observations", "static"),
    os.path.join(BASE_DIR, "importation", "static"),
]

# Dossier oÃ¹ Django collectera tous les fichiers statiques pour la mise en production
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Dossier oÃ¹ seront stockÃ© les fichiers jpg
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Chemin du dossier logs dans l'application observations
LOG_DIR = os.path.join(BASE_DIR, 'observations', 'logs')

# CrÃ©ation du dossier logs s'il n'existe pas
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{module}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'ignore_debug_toolbar_errors': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not (
                'django.template.base.VariableDoesNotExist' in record.getMessage()
                and 'toolbar' in record.getMessage()
            ),
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_debug.log'),
            'maxBytes': 5 * 1024 * 1024,   # 5 Mo max
            'backupCount': 5,              # 5 fichiers de rotation
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['ignore_debug_toolbar_errors'],
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',   # moins verbeux que DEBUG
            'propagate': True,
        },
        'observations': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'importation': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'Transcription': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.template': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Lire la version du fichier version.txt
VERSION_FILE = os.path.join(BASE_DIR, "version.txt")
try:
    with open(VERSION_FILE) as f:
        VERSION = f.read().strip()
except FileNotFoundError:
    VERSION = "0.0.0"  # Valeur par dÃ©faut en cas d'erreur

# Active Debug Toolbar uniquement si dÃ©fini dans settings_local ou .env
try:
    from .settings_local import USE_DEBUG_TOOLBAR
except (ImportError, AttributeError):
    USE_DEBUG_TOOLBAR = settings.USE_DEBUG_TOOLBAR

# settings.py (Ã la toute fin)
if USE_DEBUG_TOOLBAR:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1']
