"""
Django settings for observations_nids project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import importlib.util
import logging
import os
from pathlib import Path
from types import ModuleType
from typing import Any

from dotenv import load_dotenv

# ✅ Import Pydantic settings
from .config import get_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ Load environment variables from .env file
load_dotenv(dotenv_path=os.path.join(BASE_DIR, ".env"))


# ✅ Get settings from environment variables
settings = get_settings()

# ALLOWED_HOSTS
# Use ALLOWED_HOSTS from settings object which is loaded from config.py
ALLOWED_HOSTS = settings.ALLOWED_HOSTS

# CSRF_TRUSTED_ORIGINS (required for Django 4.0+ behind reverse proxy)
CSRF_TRUSTED_ORIGINS = settings.CSRF_TRUSTED_ORIGINS

# Tell Django to trust X-Forwarded-Proto header from reverse proxy
# This allows Django to recognize HTTPS when behind Apache/Nginx reverse proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Content Security Policy (CSP) Configuration
# Permet l'utilisation de CDN externes pour Bootstrap, Chart.js, Font Awesome
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",  # Nécessaire pour les scripts inline dans les templates
    "https://cdn.jsdelivr.net",  # Bootstrap et Chart.js
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",  # Nécessaire pour les styles inline
    "https://cdn.jsdelivr.net",  # Bootstrap
    "https://cdnjs.cloudflare.com",  # Font Awesome
)
CSP_FONT_SRC = (
    "'self'",
    "https://cdnjs.cloudflare.com",  # Font Awesome fonts
)
CSP_IMG_SRC = (
    "'self'",
    "data:",  # Images inline en base64
)
CSP_CONNECT_SRC = ("'self'",)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG

# Environment identifier (production, pilote, development)
ENVIRONMENT = settings.ENVIRONMENT

_local: ModuleType | None  # <- type déclaré une fois

# Surcharge via settings_local.py (facultatif)
try:
    from . import settings_local as _local  # type: ignore
except ImportError:
    _local = None

if _local is not None:
    DEBUG = getattr(_local, "DEBUG", DEBUG)
    SECRET_KEY = getattr(_local, "SECRET_KEY", SECRET_KEY)
    ALLOWED_HOSTS = getattr(_local, "ALLOWED_HOSTS", ALLOWED_HOSTS)


AUTH_USER_MODEL = 'accounts.Utilisateur'
LOGIN_REDIRECT_URL = '/'

# Durée de session : 3600 secondes (1 heure)
SESSION_COOKIE_AGE = settings.SESSION_COOKIE_AGE
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Déconnexion si l'utilisateur ferme son navigateur

# Celery Configuration - utilise les variables d'environnement
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requis pour django-helpdesk
    'django.contrib.humanize',
    # 'django_extensions' déplacé dans settings_local.py (dev uniquement)
    'accounts.apps.AccountsConfig',
    'core.apps.CoreConfig',
    'taxonomy.apps.TaxonomyConfig',
    'geo.apps.GeoConfig',
    'observations.apps.ObservationsConfig',
    'review.apps.ReviewConfig',
    'ingest.apps.IngestConfig',
    'audit.apps.AuditConfig',
    'ocr.apps.OcrConfig',
    'feedback.apps.FeedbackConfig',
    'bootstrap4form',  # Required for nicer formatting of forms with the default templates
    'crispy_forms',  # Add crispy_forms
    'crispy_bootstrap5',  # Add crispy_bootstrap5 for Bootstrap 5 integration
    'rest_framework',  # required for the API
    'helpdesk',
    'helpdesk_custom.apps.HelpdeskCustomConfig',  # Personnalisation de Helpdesk
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'observations.middleware.SessionExpiryMiddleware',
]

# Ajouter WhiteNoise uniquement si le package est installé (production)
if importlib.util.find_spec('whitenoise') is not None:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')  # Après SecurityMiddleware

# Ajouter CSP uniquement si le package est installé (production)
if importlib.util.find_spec('csp') is not None:
    # Insérer après WhiteNoise si présent, sinon en position 1
    whitenoise_index = next((i for i, m in enumerate(MIDDLEWARE) if 'whitenoise' in m.lower()), 0)
    MIDDLEWARE.insert(whitenoise_index + 1, 'csp.middleware.CSPMiddleware')

ROOT_URLCONF = 'observations_nids.urls'


# Configurez les adresses IP autorisées à voir la toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

# Configuration optionnelle
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # Affiche toujours la toolbar en développement
    'RENDER_PANELS': True,  # Force le rendu synchrone des panneaux (fix pour v6.0.0)
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
                'observations_nids.context_processors.environment',
            ],
        },
    },
]

WSGI_APPLICATION = 'observations_nids.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = settings.get_database_config()

# Surcharge depuis settings_local.py si présent
if _local is not None and hasattr(_local, 'DATABASES'):
    DATABASES = _local.DATABASES


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

LOGIN_URL = 'observations:login'

# --- Static & Media configuration (managed for dev/prod) ---
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT", os.path.join(BASE_DIR, "staticfiles"))

# Dossiers additionnels contenant des fichiers statiques
# La documentation MkDocs buildée sera collectée depuis site-user/ vers staticfiles/docs/
STATICFILES_DIRS = [
    ("docs", os.path.join(BASE_DIR, "site-user")),  # Build MkDocs → /static/docs/
]

# WhiteNoise configuration for static files compression and caching
# Uniquement si WhiteNoise est installé (production)
if importlib.util.find_spec('whitenoise') is not None:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # En développement sans WhiteNoise, utiliser le storage par défaut de Django
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

# Surcharge depuis settings_local.py si présent
if _local is not None:
    STATIC_ROOT = getattr(_local, "STATIC_ROOT", STATIC_ROOT)
    MEDIA_ROOT = getattr(_local, "MEDIA_ROOT", MEDIA_ROOT)
# --- End static/media ---

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Logging configuration (centralized, uses DJANGO_LOG_DIR env var in prod) ---

DEFAULT_LOG_DIR = os.path.join(BASE_DIR, 'observations', 'logs')
LOG_DIR = os.environ.get("DJANGO_LOG_DIR", DEFAULT_LOG_DIR)

# Surcharge depuis settings_local.py si présent
if _local is not None:
    LOG_DIR = getattr(_local, "LOG_DIR", LOG_DIR)

# Création du dossier logs s'il n'existe pas (seulement si dans BASE_DIR)
try:
    if str(LOG_DIR).startswith(str(BASE_DIR)):
        Path(LOG_DIR).mkdir(parents=True, exist_ok=True)
except Exception:
    pass

# Handler personnalisé pour console avec support UTF-8 sur Windows


class UTF8StreamHandler(logging.StreamHandler):
    """StreamHandler qui force l'encodage UTF-8 pour éviter les erreurs Unicode sur Windows"""

    def emit(self, record):
        try:
            msg = self.format(record)
            stream = self.stream

            # Ne pas wrapper le stream système, gérer l'encodage dans emit seulement
            try:
                # Essayer d'écrire directement
                stream.write(msg + self.terminator)
                self.flush()
            except UnicodeEncodeError:
                # Si échec d'encodage (Windows cp1252), utiliser le buffer avec UTF-8
                if hasattr(stream, 'buffer'):
                    # Écrire directement dans le buffer avec UTF-8
                    encoded_msg = (msg + self.terminator).encode('utf-8', errors='replace')
                    stream.buffer.write(encoded_msg)
                    stream.buffer.flush()
                else:
                    # Fallback : remplacer les caractères non-ASCII
                    safe_msg = msg.encode('ascii', errors='replace').decode('ascii')
                    stream.write(safe_msg + self.terminator)
                    self.flush()
        except Exception:
            self.handleError(record)


LOGGING: dict[str, Any] = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{module}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_debug.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Support Unicode (œ, é, etc.)
        },
        'console': {
            'level': 'DEBUG',
            '()': UTF8StreamHandler,  # Handler personnalisé avec support UTF-8
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'observations': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Surcharge du niveau de log depuis settings_local.py si présent
if _local is not None and hasattr(_local, 'LOG_LEVEL'):
    LOGGING['handlers']['file']['level'] = _local.LOG_LEVEL
    LOGGING['loggers']['django']['level'] = _local.LOG_LEVEL
# --- End Logging ---


# Lire la version du fichier version.txt
VERSION_FILE = os.path.join(BASE_DIR, "version.txt")
try:
    with open(VERSION_FILE) as f:
        VERSION = f.read().strip()
except FileNotFoundError:
    VERSION = "0.0.0"  # Valeur par défaut en cas d'erreur

# --- Email Configuration ---
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@observations-nids.fr')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', '')

# Surcharge depuis settings_local.py si présent
if _local is not None:
    EMAIL_BACKEND = getattr(_local, 'EMAIL_BACKEND', EMAIL_BACKEND)
    EMAIL_HOST = getattr(_local, 'EMAIL_HOST', EMAIL_HOST)
    EMAIL_PORT = getattr(_local, 'EMAIL_PORT', EMAIL_PORT)
    EMAIL_USE_TLS = getattr(_local, 'EMAIL_USE_TLS', EMAIL_USE_TLS)
    EMAIL_HOST_USER = getattr(_local, 'EMAIL_HOST_USER', EMAIL_HOST_USER)
    EMAIL_HOST_PASSWORD = getattr(_local, 'EMAIL_HOST_PASSWORD', EMAIL_HOST_PASSWORD)
    DEFAULT_FROM_EMAIL = getattr(_local, 'DEFAULT_FROM_EMAIL', DEFAULT_FROM_EMAIL)
    ADMIN_EMAIL = getattr(_local, 'ADMIN_EMAIL', ADMIN_EMAIL)
# --- End Email Configuration ---

# Active Debug Toolbar uniquement si défini dans settings_local ou .env
try:
    from . import settings_local as _local_debug  # type: ignore[attr-defined]

    USE_DEBUG_TOOLBAR = getattr(_local_debug, 'USE_DEBUG_TOOLBAR', settings.USE_DEBUG_TOOLBAR)
except ImportError:
    USE_DEBUG_TOOLBAR = settings.USE_DEBUG_TOOLBAR

# settings.py (à la toute fin)
if USE_DEBUG_TOOLBAR:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1']

# django-helpdesk settings definition
HELPDESK_TEAMS_MODE_ENABLED = False
SITE_ID = 1

# 🔒 Sécurité : Désactiver l'accès public
# Seuls les utilisateurs connectés peuvent accéder à Helpdesk
HELPDESK_SUBMIT_A_TICKET_PUBLIC = False
HELPDESK_VIEW_A_TICKET_PUBLIC = False

# Utiliser nos formulaires personnalisés
HELPDESK_PUBLIC_TICKET_FORM_CLASS = 'helpdesk_custom.forms.CustomPublicTicketForm'
HELPDESK_TICKET_FORM_CLASS = 'helpdesk_custom.forms.CustomTicketForm'

# Crispy Forms Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
