# Generated by Django 6.0 on 2026-01-11 17:56

from django.db import migrations


def rename_table(apps, schema_editor):
    """Renomme la table pilot_transcription_ocr en ocr_transcription_ocr"""
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la table pilot_transcription_ocr existe
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = 'pilot_transcription_ocr'"
        )
        if cursor.fetchone()[0] > 0:
            # Renommer la table
            cursor.execute("RENAME TABLE pilot_transcription_ocr TO ocr_transcription_ocr")


def reverse_rename_table(apps, schema_editor):
    """Opération inverse: renomme ocr_transcription_ocr en pilot_transcription_ocr"""
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la table ocr_transcription_ocr existe
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = 'ocr_transcription_ocr'"
        )
        if cursor.fetchone()[0] > 0:
            # Renommer la table
            cursor.execute("RENAME TABLE ocr_transcription_ocr TO pilot_transcription_ocr")


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_update_gemini_models'),
    ]

    operations = [
        migrations.RunPython(rename_table, reverse_rename_table),
    ]
