# Generated by Django 6.0 on 2026-01-11 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_configurationverrouillage_and_more'),
        ('ocr', '0004_rename_pilot_tables_to_ocr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptionocr',
            options={'ordering': ['-date_transcription'], 'verbose_name': 'Transcription OCR', 'verbose_name_plural': 'Transcriptions OCR'},
        ),
        # Renommage des index via SQL brut (car la table a déjà été renommée en 0004)
        migrations.RunSQL(
            sql="ALTER TABLE ocr_transcription_ocr RENAME INDEX pilot_trans_fiche_i_0e707c_idx TO ocr_transcr_fiche_i_830756_idx",
            reverse_sql="ALTER TABLE ocr_transcription_ocr RENAME INDEX ocr_transcr_fiche_i_830756_idx TO pilot_trans_fiche_i_0e707c_idx",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE ocr_transcription_ocr RENAME INDEX pilot_trans_statut__7be669_idx TO ocr_transcr_statut__b0f687_idx",
            reverse_sql="ALTER TABLE ocr_transcription_ocr RENAME INDEX ocr_transcr_statut__b0f687_idx TO pilot_trans_statut__7be669_idx",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE ocr_transcription_ocr RENAME INDEX pilot_trans_score_g_a3a215_idx TO ocr_transcr_score_g_0a1c56_idx",
            reverse_sql="ALTER TABLE ocr_transcription_ocr RENAME INDEX ocr_transcr_score_g_0a1c56_idx TO pilot_trans_score_g_a3a215_idx",
        ),
        migrations.AlterField(
            model_name='transcriptionocr',
            name='fiche',
            field=models.ForeignKey(blank=True, help_text="Fiche d'observation corrigée manuellement (vérité terrain)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions_ocr', to='observations.ficheobservation', verbose_name='Fiche de référence'),
        ),
        # AlterModelTable supprimé car la table a déjà été renommée dans 0004_rename_pilot_tables_to_ocr
    ]
