# Generated by Django on 2026-01-14

from django.db import migrations


def rename_indexes_and_table_if_needed(apps, schema_editor):
    """Renomme les index et la table seulement s'ils existent avec les anciens noms"""
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la table pilot_transcription_ocr existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'pilot_transcription_ocr'
        """)
        if cursor.fetchone()[0] > 0:
            # Renommer la table
            cursor.execute("RENAME TABLE pilot_transcription_ocr TO ocr_transcription_ocr")
        
        # Vérifier quels index existent avec les anciens noms sur ocr_transcription_ocr
        cursor.execute("""
            SELECT INDEX_NAME 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'ocr_transcription_ocr'
            AND INDEX_NAME LIKE 'pilot_trans_%'
        """)
        existing_indexes = {row[0] for row in cursor.fetchall()}
        
        # Renommer seulement les index qui existent
        rename_map = {
            'pilot_trans_fiche_i_0e707c_idx': 'ocr_transcr_fiche_i_830756_idx',
            'pilot_trans_statut__7be669_idx': 'ocr_transcr_statut__b0f687_idx',
            'pilot_trans_score_g_a3a215_idx': 'ocr_transcr_score_g_0a1c56_idx',
        }
        
        for old_name, new_name in rename_map.items():
            if old_name in existing_indexes:
                try:
                    cursor.execute(f"ALTER TABLE ocr_transcription_ocr RENAME INDEX `{old_name}` TO `{new_name}`")
                except Exception:
                    # Ignorer si l'index n'existe pas ou est déjà renommé
                    pass


def reverse_rename(apps, schema_editor):
    """Opération inverse (non utilisée normalement)"""
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la table ocr_transcription_ocr existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'ocr_transcription_ocr'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("RENAME TABLE ocr_transcription_ocr TO pilot_transcription_ocr")
        
        rename_map = {
            'ocr_transcr_fiche_i_830756_idx': 'pilot_trans_fiche_i_0e707c_idx',
            'ocr_transcr_statut__b0f687_idx': 'pilot_trans_statut__7be669_idx',
            'ocr_transcr_score_g_0a1c56_idx': 'pilot_trans_score_g_a3a215_idx',
        }
        
        cursor.execute("""
            SELECT INDEX_NAME 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'pilot_transcription_ocr'
            AND INDEX_NAME LIKE 'ocr_transcr_%'
        """)
        existing_indexes = {row[0] for row in cursor.fetchall()}
        
        for new_name, old_name in rename_map.items():
            if new_name in existing_indexes:
                try:
                    cursor.execute(f"ALTER TABLE pilot_transcription_ocr RENAME INDEX `{new_name}` TO `{old_name}`")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_rename_pilot_trans_fiche_i_0e707c_idx_ocr_transcr_fiche_i_830756_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_and_table_if_needed, reverse_rename),
    ]
