# Generated by Django 6.0.1 on 2026-01-31 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_rename_pilot_trans_fiche_i_0e707c_idx_ocr_transcr_fiche_i_830756_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionocr',
            name='score_numerique',
            field=models.FloatField(blank=True, help_text='Score de précision des données structurées (Dates, Chiffres)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score Numérique (%)'),
        ),
        migrations.AddField(
            model_name='transcriptionocr',
            name='score_texte',
            field=models.FloatField(blank=True, help_text='Score de similarité sémantique (Espèce, Commune, Textes libres)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score Texte (%)'),
        ),
    ]
