# Generated by Django 6.0.1 on 2026-02-01 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_add_incertitude_fields'),
        ('ocr', '0008_rename_pilot_trans_fiche_i_0e707c_idx_ocr_transcr_fiche_i_830756_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transcriptionocr',
            name='ocr_transcr_fiche_i_830756_idx',
        ),
        migrations.RemoveIndex(
            model_name='transcriptionocr',
            name='ocr_transcr_statut__b0f687_idx',
        ),
        migrations.RemoveIndex(
            model_name='transcriptionocr',
            name='ocr_transcr_score_g_0a1c56_idx',
        ),
        migrations.AddField(
            model_name='transcriptionocr',
            name='erreur_message',
            field=models.TextField(blank=True, help_text="Détails de l'erreur le cas échéant", verbose_name="Message d'erreur"),
        ),
        migrations.AddField(
            model_name='transcriptionocr',
            name='statut',
            field=models.CharField(choices=[('succes', 'Succès'), ('erreur', 'Erreur'), ('en_cours', 'En cours')], default='en_cours', max_length=20, verbose_name='Statut du traitement'),
        ),
        migrations.AlterField(
            model_name='transcriptionocr',
            name='chemin_image',
            field=models.CharField(help_text="Chemin de l'image utilisée pour cette transcription", max_length=255, verbose_name="Chemin de l'image source"),
        ),
        migrations.AlterField(
            model_name='transcriptionocr',
            name='chemin_json',
            field=models.CharField(help_text='Chemin vers le fichier JSON de la transcription OCR', max_length=255, verbose_name='Chemin du fichier JSON'),
        ),
        migrations.AlterField(
            model_name='transcriptionocr',
            name='fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions_ocr', to='observations.ficheobservation', verbose_name='Fiche de référence'),
        ),
        migrations.AlterField(
            model_name='transcriptionocr',
            name='modele_ocr',
            field=models.CharField(default='gemini_3_flash', max_length=50, verbose_name='Modèle OCR'),
        ),
        migrations.AlterField(
            model_name='transcriptionocr',
            name='temps_traitement_secondes',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Temps de traitement (s)'),
        ),
        migrations.AddIndex(
            model_name='transcriptionocr',
            index=models.Index(fields=['fiche'], name='ocr_transcr_fiche_i_b5f29c_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionocr',
            index=models.Index(fields=['statut'], name='ocr_transcr_statut_c0cff9_idx'),
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='date_evaluation',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='details_comparaison',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='nombre_champs_corrects',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='nombre_champs_total',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='nombre_erreurs_dates',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='nombre_erreurs_especes',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='nombre_erreurs_lieux',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='nombre_erreurs_nombres',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='nombre_erreurs_texte',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='notes_evaluation',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='score_global',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='statut_evaluation',
        ),
        migrations.RemoveField(
            model_name='transcriptionocr',
            name='type_image',
        ),
    ]
