# Generated by Django 6.0.1 on 2026-01-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_transcriptionocr_score_numerique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionocr',
            name='traitement_image',
            field=models.CharField(blank=True, help_text='Nom du traitement appliqué (ex: binarisation, blur, etc.)', max_length=50, verbose_name='Traitement spécifique'),
        ),
    ]
